# Generated by Django 2.0.3 on 2018-03-29 22:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationID', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('local', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=5)),
                ('ruler', models.CharField(max_length=15)),
                ('gov', models.CharField(choices=[('MA', 'Monarchy [Absoulte]'), ('MC', 'Monarchy [Constitutional]'), ('RO', 'Republic [Oligarchic]'), ('RC', 'Republic [Constitutional]'), ('RP', 'Republic [Plutocratic]'), ('RS', 'Republic [Socialist]'), ('DF', 'Dictatorship [Fascist]'), ('DS', 'Dictatorship [Socialist]'), ('TO', 'Theocracy'), ('TR', 'Tribal')], default='MA', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='NationPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationID', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('points', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
            ],
        ),
    ]
